name: Deploy

on:
  push:
    branches:
      - main
jobs:
  main-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: Run  composer install
        run: composer install -n --prefer-dist
      - name: Deploy Application
        run: |
          cp .env.example .env
          php artisan key:generate
